export const HANDLE_LOADING = 'HANDLE_LOADING';
export const HANDLE_REFRESHING = 'HANDLE_REFRESHING';
export const HANDLE_RADIO = 'HANDLE_RADIO';
export const HANDLE_INPUT_TEXT = 'HANDLE_INPUT_TEXT';
export const CHECK_FLAT_EXAMINATION = 'CHECK_FLAT_EXAMINATION';
export const UNCHECK_FLAT_EXAMINATION = 'UNCHECK_FLAT_EXAMINATION';